### ISSUE TITLE
Build failure for the application

### ISSUE THREAD

**Issue by harshad16** [thoth-station/unresolved-package-handler#46]
**Describe the bug**
```
Installing collected packages: yarl
Successfully installed yarl-1.4.2
---> Installing application ...
Processing /opt/app-root/src
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
    Preparing wheel metadata: started
    Preparing wheel metadata: finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: /opt/app-root/bin/python3.6 /opt/app-root/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpz8ufmv9n
         cwd: /tmp/pip-req-build-yonafooa
    Complete output (10 lines):
    Traceback (most recent call last):
      File "/opt/app-root/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
        main()
      File "/opt/app-root/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/opt/app-root/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 133, in prepare_metadata_for_build_wheel
        return hook(metadata_directory, config_settings)
      File "/tmp/pip-build-env-6p8a8wa3/overlay/lib/python3.6/site-packages/setuptools/build_meta.py", line 173, in prepare_metadata_for_build_wheel
        assert len(dist_infos) == 1
    AssertionError
    ----------------------------------------
ERROR: Command errored out with exit status 1: /opt/app-root/bin/python3.6 /opt/app-root/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpz8ufmv9n Check the logs for full command output.
subprocess exited with status 1
subprocess exited with status 1
error building at STEP "RUN /usr/libexec/s2i/assemble": exit status 1
```

**Additional context**
http://tekton-dashboard-tekton-pipelines.apps.thoth01.lab.upshift.rdu2.redhat.com/#/namespaces/thoth-ci/pipelineruns/tag-release-cffxc

**Comment by harshad16** [comment]
The setup.py needs to have `setuptools.setup` in it. 
Absence of setup in setup.py causes issues while `prepare_metadata_for_build_wheel` function is executing.
