### ISSUE TITLE
unresolved consumer is crash looping

### ISSUE THREAD

**Issue by harshad16** [thoth-station/unresolved-package-handler#58]
**Describe the bug**
The deployment of unresolved consumer is crash looping due to missing thoth-messaging

**To Reproduce**
1. Go to ocp cluster
2. Click on 'https://console-openshift-console.apps.ocp.prod.psi.redhat.com/k8s/ns/thoth-test-core/pods/unresolved-package-handler-consumer-1-k9r4p/logs'
3. Scroll down 

**Additional context**
```
/opt/app-root/src/app.sh: line 17: [: missing `]'
Traceback (most recent call last):
  File "/opt/app-root/bin/faust", line 8, in <module>
    sys.exit(cli())
  File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 781, in main
    with self.make_context(prog_name, args, **extra) as ctx:
  File "/opt/app-root/lib/python3.6/site-packages/faust/cli/base.py", line 407, in make_context
    self._maybe_import_app()
  File "/opt/app-root/lib/python3.6/site-packages/faust/cli/base.py", line 372, in _maybe_import_app
    find_app(appstr)
  File "/opt/app-root/lib/python3.6/site-packages/faust/cli/base.py", line 299, in find_app
    val = symbol_by_name(app, imp=imp)
  File "/opt/app-root/lib/python3.6/site-packages/mode/utils/imports.py", line 269, in symbol_by_name
    **kwargs)
  File "/opt/app-root/lib/python3.6/site-packages/mode/utils/imports.py", line 376, in import_from_cwd
    return imp(module, package=package)
  File "/opt/app-root/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/app-root/src/consumer.py", line 23, in <module>
    from thoth.messaging import MessageBase, UnresolvedPackageMessage
ModuleNotFoundError: No module named 'thoth-messaging'
```

**Comment by harshad16** [comment]
@pacospace

**Comment by pacospace** [comment]
> @pacospace

https://github.com/thoth-station/unresolved-package-handler/pull/59 Thanks! @harshad16

**Comment by pacospace** [comment]
there was no import in init in thoth-messaging so that class could not be imported :/ https://github.com/thoth-station/messaging/pull/144
